export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_LOCAL_STORAGE = 'CART_SAVE_LOCAL_STORAGE';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ORDER_SUCCESSFUL = 'ORDER_SUCCESSFUL';
